CREATE TABLE hitchcocktober_days (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  day INTEGER,
  movie_id INTEGER,
  movie TEXT,
  meal JSON,
  rating INTEGER,
  user_id INTEGER
    REFERENCES hitchcocktober_users(id) ON DELETE CASCADE NOT NULL
);